# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\Screens\LoginScreen - Copia.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import ImageAndIcons

class Ui_LoginScreen(object):
    def setupUi(self, LoginScreen):
        #### Default's ####
        LoginScreen.setObjectName("LoginScreen")
        LoginScreen.resize(360, 450)
        LoginScreen.setWindowFlag(QtCore.Qt.FramelessWindowHint)
        LoginScreen.setAttribute(QtCore.Qt.WA_TranslucentBackground)
        LoginScreen.setStyleSheet(

"#BackgroundFrame{\n"
"    background-image: url(:/newPrefix/Icons/BackGroundLogin.png);\n"
"    background-position: center;\n"
"    border-radius:25px;\n"
"}\n"

"#MainFrame{\n"
"    background-color: rgba(26, 84, 191,0.7);\n"
"    border-radius:25px;\n"
"}\n"

"#ExitBtn{\n"
"    image: url(:/newPrefix/Icons/Btt_Exit.png);\n"
"    border-radius:25px;\n"
"}\n"

"#ExitBtn:hover{\n"
"    image: url(:/newPrefix/Icons/Btt_Exit_Hover.png);\n"
"    border-radius:25px;\n"
"}\n"

"#LabelBody01{\n"
"    background-color: rgba(229, 229, 229,0.3);\n"
"    color: rgb(229, 229, 229);\n"
"    font: 40pt \"Agency FB\";\n"
"    border-radius:15px;\n"
"}\n"

"#LoginBtn{\n"
"    border-radius:25px;\n"
"    image: url(:/newPrefix/Icons/Btt_Login.png);\n"
"}\n"

"#LoginBtn:hover{\n"
"    border-radius:25px;\n"
"    image: url(:/newPrefix/Icons/Btt_Login_Hover.png);\n"
"}"
)
        self.BackgroundFrame = QtWidgets.QFrame(LoginScreen)
        self.BackgroundFrame.setObjectName("BackgroundFrame")
        self.BackgroundFrame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.BackgroundFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.BackgroundFrame.setLineWidth(0)
        
        self.MainFrame = QtWidgets.QFrame(self.BackgroundFrame)
        self.MainFrame.setObjectName("MainFrame")
        self.MainFrame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.MainFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        
        self.HeaderFrame = QtWidgets.QFrame(self.MainFrame)
        self.HeaderFrame.setObjectName("HeaderFrame")
        self.HeaderFrame.setMaximumSize(QtCore.QSize(16777215, 50))
        self.HeaderFrame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.HeaderFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.HeaderFrame.setLineWidth(0)
        
        self.ExitBtn = QtWidgets.QPushButton(self.HeaderFrame)
        self.ExitBtn.setObjectName("ExitBtn")
        self.ExitBtn.setMinimumSize(QtCore.QSize(50, 50))
        self.ExitBtn.setMaximumSize(QtCore.QSize(50, 50))
        self.ExitBtn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.ExitBtn.setText("")
        self.ExitBtn.setIconSize(QtCore.QSize(50, 50))
        self.ExitBtn.setFlat(True)
        self.ExitBtn.clicked.connect(self.ExitFunc)
        
        self.BodyFrame = QtWidgets.QFrame(self.MainFrame)
        self.BodyFrame.setObjectName("BodyFrame")
        self.BodyFrame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.BodyFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        
        self.LabelBody01 = QtWidgets.QLabel(self.BodyFrame)
        self.LabelBody01.setObjectName("LabelBody01")
        self.LabelBody01.setAlignment(QtCore.Qt.AlignCenter)
        
        self.FooterFrame = QtWidgets.QFrame(self.MainFrame)
        self.FooterFrame.setObjectName("FooterFrame")
        self.FooterFrame.setMinimumSize(QtCore.QSize(0, 50))
        self.FooterFrame.setMaximumSize(QtCore.QSize(16777215, 50))
        self.FooterFrame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.FooterFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        
        self.LoginBtn = QtWidgets.QPushButton(self.FooterFrame)
        self.LoginBtn.setObjectName("LoginBtn")
        self.LoginBtn.setMinimumSize(QtCore.QSize(150, 50))
        self.LoginBtn.setMaximumSize(QtCore.QSize(150, 50))
        self.LoginBtn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.LoginBtn.setText("")
        self.LoginBtn.setIconSize(QtCore.QSize(150, 50))
        self.LoginBtn.setFlat(True)
        self.LoginBtn.clicked.connect(self.LoginFunc)
        
        Separator00 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        Separator01 = QtWidgets.QSpacerItem(20, 108, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        Separator02 = QtWidgets.QSpacerItem(20, 108, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)

        self.verticalLayout00 = QtWidgets.QVBoxLayout(LoginScreen)
        self.verticalLayout00.setObjectName("verticalLayout")
        self.verticalLayout00.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout00.setSpacing(0)

        self.verticalLayout01 = QtWidgets.QVBoxLayout(self.BackgroundFrame)
        self.verticalLayout01.setObjectName("verticalLayout_4")
        self.verticalLayout01.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout01.setSpacing(0)

        self.verticalLayout02 = QtWidgets.QVBoxLayout(self.MainFrame)
        self.verticalLayout02.setObjectName("verticalLayout_2")
        self.verticalLayout02.setContentsMargins(30, 30, 30, 30)
        self.verticalLayout02.setSpacing(0)

        self.verticalLayout03 = QtWidgets.QVBoxLayout(self.BodyFrame)
        self.verticalLayout03.setObjectName("verticalLayout_3")
        self.verticalLayout03.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout03.setSpacing(0)

        self.horizontalLayout00 = QtWidgets.QHBoxLayout(self.HeaderFrame)
        self.horizontalLayout00.setObjectName("horizontalLayout")
        self.horizontalLayout00.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout00.setSpacing(0)

        self.horizontalLayout01 = QtWidgets.QHBoxLayout(self.FooterFrame)
        self.horizontalLayout01.setObjectName("horizontalLayout_2")
        self.horizontalLayout01.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout01.setSpacing(0)

        self.verticalLayout00.addWidget(self.BackgroundFrame)
        self.verticalLayout01.addWidget(self.MainFrame)
        self.verticalLayout02.addWidget(self.HeaderFrame)
        self.verticalLayout02.addWidget(self.BodyFrame)
        self.verticalLayout02.addWidget(self.FooterFrame)
        self.verticalLayout03.addItem(Separator01)
        self.verticalLayout03.addWidget(self.LabelBody01)
        self.verticalLayout03.addItem(Separator02)
        self.horizontalLayout00.addItem(Separator00)
        self.horizontalLayout00.addWidget(self.ExitBtn)
        self.horizontalLayout01.addWidget(self.LoginBtn)

        self.retranslateUi(LoginScreen)
        QtCore.QMetaObject.connectSlotsByName(LoginScreen)

    def retranslateUi(self, LoginScreen):
        _translate = QtCore.QCoreApplication.translate
        LoginScreen.setWindowTitle(_translate("LoginScreen", "Form"))
        self.LabelBody01.setText(_translate("LoginScreen", "Central Bank"))

    def ExitFunc(self):
        LoginScreen.close()

    def LoginFunc(self):
        print('Logado')

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    LoginScreen = QtWidgets.QWidget()
    ui = Ui_LoginScreen()
    ui.setupUi(LoginScreen)
    LoginScreen.show()
    sys.exit(app.exec_())
